#!/bin/bash
# Prevents pushing to master or development branches
# ideas and some code from comments to https://gist.github.com/pixelhandler/5718585

BRANCH=`git rev-parse --abbrev-ref HEAD`
PUSH_COMMAND=`ps -ocommand= -p $PPID`
PROTECTED_BRANCHES="^(master|development)"

RED='\033[0;31m'
NC='\033[0m' # No Color

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]; then
        echo
        echo -e "${RED}Prevented push to protected branch \"$BRANCH\" by using a pre-push hook.${NC}"
        echo "You should submit a pull request on Github instead."
        echo
        echo "If you want to skip this check, invoke again with --no-verify "
        echo
        exit 1
fi

exit 0
